### ISSUE TITLE
err  TypeError: undefined is not a function

### ISSUE THREAD

**Issue by jtamary** [frankwallis/plugin-typescript#116]
Hey,

I've encountered a problem while bundling on our build machines which I cannot reproduce on my local machine.
It seems similar to [#1662](https://github.com/jspm/jspm-cli/issues/1662), however, the error is different 

Any help would be appreciated,
Jonathan 

```
     Building the bundle tree for src...

err  TypeError: undefined is not a function
      at getNodeSystem (/home/tamarj/branches/amber_dashboard/src/management/RPVWCJsClient/client/jspm_packages/npm/typescript@1.8.9/lib/typescript.js:2051:32)
      at eval (/home/tamarj/branches/amber_dashboard/src/management/RPVWCJsClient/client/jspm_packages/npm/typescript@1.8.9/lib/typescript.js:2241:20)
      at ts (/home/tamarj/branches/amber_dashboard/src/management/RPVWCJsClient/client/jspm_packages/npm/typescript@1.8.9/lib/typescript.js:2249:7)
      at Object.eval (/home/tamarj/branches/amber_dashboard/src/management/RPVWCJsClient/client/jspm_packages/npm/typescript@1.8.9/lib/typescript.js:2250:3)
      at eval (/home/tamarj/branches/amber_dashboard/src/management/RPVWCJsClient/client/jspm_packages/npm/typescript@1.8.9/lib/typescript.js:54798:4)
      at eval (native)
  Evaluating /home/tamarj/branches/amber_dashboard/src/management/RPVWCJsClient/client/jspm_packages/npm/typescript@1.8.9/lib/typescript.js
  Error loading /home/tamarj/branches/amber_dashboard/src/management/RPVWCJsClient/client/jspm_packages/github/frankwallis/plugin-typescript@4.0.5/plugin.js
```

**Comment by frankwallis** [comment]
It does look related to the other issue, have you tried updating the overrides with ```jspm install npm:typescript -o```

I am also starting to think that there is different behaviour depending on what platform you are running on, can you confirm what operating system and node versions you are using on your build and dev machine?
