### ISSUE TITLE
Can't run example: Cannot find module 'http-server'

### ISSUE THREAD

**Issue by johnjelinek** [frankwallis/plugin-typescript#134]
```
npm start

> @ start /Users/administrator/Projects/plugin-typescript/examples/react
> node ../tasks/start

module.js:340
    throw err;
    ^

Error: Cannot find module 'http-server'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/administrator/Projects/plugin-typescript/examples/tasks/start.js:1:73)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)

npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/administrator/.nvm/versions/node/v5.1.0/bin/node" "/Users/administrator/.nvm/versions/node/v5.1.0/bin/npm" "start"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! @ start: `node ../tasks/start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script 'node ../tasks/start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ../tasks/start
npm ERR! You can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/administrator/Projects/plugin-typescript/examples/react/npm-debug.log
```

**Comment by johnjelinek** [comment]
oops, forgot these steps:
```
> cd plugin-typescript
> npm install
```
