### ISSUE TITLE
jspm bundle fails with require is not defined.

### ISSUE THREAD

**Issue by adamduren** [frankwallis/plugin-typescript#141]
I'm at a loss. Does anyone have any idea what would be causing this?
```
$ jspm bundle ggf/ggf/static/app
     Building the bundle tree for ggf/ggf/static/app...

err  C:/Users/adamd/workspace/ggf/jspm_packages/npm/typescript@1.8.10/lib/typescript.js:48519
        })(require('@empty'));
           ^
        ReferenceError: require is not defined
            at C:/Users/adamd/workspace/ggf/jspm_packages/npm/typescript@1.8.10/lib/typescript.js:48519:4
            at Object.exports.runInThisContext (vm.js:54:17)
        Evaluating C:/Users/adamd/workspace/ggf/jspm_packages/npm/typescript@1.8.10/lib/typescript.js
        Error loading C:/Users/adamd/workspace/ggf/jspm_packages/github/frankwallis/plugin-typescript@4.0.16/plugin.js
```

**Comment by adamduren** [comment]
Not sure what the issue was but upgrading to the latest beta of JSPM seemed to fix the issue.
