### ISSUE TITLE
TypeError: Cannot read property 'charCodeAt' of undefined

### ISSUE THREAD

**Issue by tamird** [frankwallis/plugin-typescript#144]
After upgrading to 5.0.1, I see the following error:
```
github.com/cockroachdb/cockroach/ui $ make embedded.go
...
jspm bundle-sfx app/app build/app.js
     Building the single-file sfx bundle for app/app...
TypeScript transpiling to CommonJS, consider setting module: "system" in typescriptOptions to transpile directly to System.register format

err  Error on translate for typings/globals/react-redux/index.d.ts!github:frankwallis/plugin-typescript@5.0.1/plugin.js at file:///Users/tamird/src/go/src/github.com/cockroachdb/cockroach/ui/typings/globals/react-redux/index.d.ts!file:///Users/tamird/src/go/src/github.com/cockroachdb/cockroach/ui/jspm_packages/github/frankwallis/plugin-typescript@5.0.1/plugin.js
	Loading typings/index.d.ts!github:frankwallis/plugin-typescript@5.0.1/plugin.js
	Loading app/app.tsx
	TypeError: Cannot read property 'charCodeAt' of undefined
         at getRootLength (file:///Users/tamird/src/go/src/github.com/cockroachdb/cockroach/ui/jspm_packages/npm/typescript@2.0.0/lib/typescript.js:1348:15)
         at isRootedDiskPath (file:///Users/tamird/src/go/src/github.com/cockroachdb/cockroach/ui/jspm_packages/npm/typescript@2.0.0/lib/typescript.js:1409:14)
         at Object.toPath (file:///Users/tamird/src/go/src/github.com/cockroachdb/cockroach/ui/jspm_packages/npm/typescript@2.0.0/lib/typescript.js:841:34)
         at processImportedModules (file:///Users/tamird/src/go/src/github.com/cockroachdb/cockroach/ui/jspm_packages/npm/typescript@2.0.0/lib/typescript.js:40833:48)
         at findSourceFile (file:///Users/tamird/src/go/src/github.com/cockroachdb/cockroach/ui/jspm_packages/npm/typescript@2.0.0/lib/typescript.js:40756:11)
         at processSourceFile (file:///Users/tamird/src/go/src/github.com/cockroachdb/cockroach/ui/jspm_packages/npm/typescript@2.0.0/lib/typescript.js:40681:23)
         at processRootFile (file:///Users/tamird/src/go/src/github.com/cockroachdb/cockroach/ui/jspm_packages/npm/typescript@2.0.0/lib/typescript.js:40600:9)
         at file:///Users/tamird/src/go/src/github.com/cockroachdb/cockroach/ui/jspm_packages/npm/typescript@2.0.0/lib/typescript.js:40104:18
         at Object.forEach (file:///Users/tamird/src/go/src/github.com/cockroachdb/cockroach/ui/jspm_packages/npm/typescript@2.0.0/lib/typescript.js:855:24)
         at Module.createProgram (file:///Users/tamird/src/go/src/github.com/cockroachdb/cockroach/ui/jspm_packages/npm/typescript@2.0.0/lib/typescript.js:40103:12)
         at TypeChecker.getAllDiagnostics (file:///Users/tamird/src/go/src/github.com/cockroachdb/cockroach/ui/jspm_packages/github/frankwallis/plugin-typescript@5.0.1/type-checker.js:83:38)
         at TypeChecker.check (file:///Users/tamird/src/go/src/github.com/cockroachdb/cockroach/ui/jspm_packages/github/frankwallis/plugin-typescript@5.0.1/type-checker.js:36:37)
         at file:///Users/tamird/src/go/src/github.com/cockroachdb/cockroach/ui/jspm_packages/github/frankwallis/plugin-typescript@5.0.1/plugin.js:60:46
make: *** [build/app.js] Error 1
```

This code is available at https://github.com/tamird/cockroach/tree/ui-ts-next. `make -C ui embedded.go` should trigger this mess.

**Comment by frankwallis** [comment]
Thanks, this should be resolved in the latest release. I think there has been a breaking change when augmenting the ```global``` interface in typescript@2.0.0 but I need to trace it through further. For now I have just changed it to output a warning in this scenario:
```file:///Users/frank/work/cockroach/ui/typings/modules/chai/index.d.ts -> global could not be resolved```. This warning can safely be ignored for now.

**Comment by frankwallis** [comment]
Raised https://github.com/Microsoft/TypeScript/issues/10023

**Comment by frankwallis** [comment]
I have improved the error reporting for the missing module error in 5.0.11, I'm closing this issue and will wait and see if there is any response to Microsoft/TypeScript#10023.
