### ISSUE TITLE
rxjs Observable.d.ts Parameter declaration expected error

### ISSUE THREAD

**Issue by nicklasb** [frankwallis/plugin-typescript#186]
It seems that that jspm install ts causes the 4.0.16 version to be loaded instead of the 6.0.1 version.
So I have to manually set the devConfig for ts to 6.0.1 to get things working.

Is this a bug, or something I am doing wrong? I admin I am not *that* knowledgeable..

**Comment by nicklasb** [comment]
However if I do that, I will just run into another problem:

````
Error: (SystemJS) Cannot read property 'map' of undefined
	TypeError: Cannot read property 'map' of undefined
	    at Resolver.resolveDependencies (https://127.0.0.1:8080/admin/jspm_packages/github/frankwallis/plugin-typescript@6.0.1/plugin.js:695:25)
	    at Resolver.resolve (https://127.0.0.1:8080/admin/jspm_packages/github/frankwallis/plugin-typescript@6.0.1/plugin.js:672:57)
	    at SystemJSLoader.eval (https://127.0.0.1:8080/admin/jspm_packages/github/frankwallis/plugin-typescript@6.0.1/plugin.js:355:45)
	    at step (https://127.0.0.1:8080/admin/jspm_packages/github/frankwallis/plugin-typescript@6.0.1/plugin.js:77:31)
	    at Object.eval [as next] (https://127.0.0.1:8080/admin/jspm_packages/github/frankwallis/plugin-typescript@6.0.1/plugin.js:26:57)
	    at fulfilled (https://127.0.0.1:8080/admin/jspm_packages/github/frankwallis/plugin-typescript@6.0.1/plugin.js:7:32)
	Error loading https://127.0.0.1:8080/admin/main.ts

````
Apparently, this code that causes the problem:

````
                    var resolvedTypes = info.typeReferenceDirectives
                        .map(function (typ) { return _this.resolveTypeReference(typ.fileName, sourceName, options); });
````

**Comment by frankwallis** [comment]
It sounds to me like you are now running against an old version of typescript, I would suggest deleting jspm_packages and all the map configuration in system.config.js and doing a clean install. Also what version of jspm are you using, I would recommend the 0.17-beta version - see the example projects in this repo for a working setup.

**Comment by nicklasb** [comment]
@frankwallis Thanks! 

That fixed the double install, however now I am getting the "SystemJS.fetch is not a function" instead.
https://github.com/frankwallis/plugin-typescript/issues/187

Closing this, however!
