### ISSUE TITLE
Error when use jspm install

### ISSUE THREAD

**Issue by felixbillon** [frankwallis/plugin-typescript#24]
Hi,

I got this error when I use cmd jspm install on exemple folder : 

```
 Looking up github:angular/bower-angular
     Updating registry cache...
ok   Up to date - angular as github:angular/bower-angular@^1.3.15 (1.4.1)
ok   Install tree has no forks.

err  TypeError: Cannot call method 'forEach' of undefined
         at C:\Users\test\AppData\Roaming\npm\node_modules\jspm\lib\core.js:212:11
         at tryCatchReject (C:\Users\test\AppData\Roaming\npm\node_modules\jspm\node_modules\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.src
.js:1183:30)
         at runContinuation1 (C:\Users\test\AppData\Roaming\npm\node_modules\jspm\node_modules\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.s
rc.js:1142:4)
         at Fulfilled.when (C:\Users\test\AppData\Roaming\npm\node_modules\jspm\node_modules\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.src
.js:930:4)
         at ContinuationTask.run (C:\Users\felix\AppData\Roaming\npm\node_modules\jspm\node_modules\systemjs\node_modules\es6-module-loader\dist\es6-module-load
er.src.js:1040:24)
         at Scheduler._drain (C:\Users\test\AppData\Roaming\npm\node_modules\jspm\node_modules\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.s
rc.js:97:19)
         at Scheduler.drain (C:\Users\test\AppData\Roaming\npm\node_modules\jspm\node_modules\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.sr
c.js:62:9)
         at process._tickCallback (node.js:415:13)

warn Installation changes not saved

```

Anyone have an idea ?

**Comment by gavares** [comment]
I had the same issue this morning. Upgraded to jspm 0.16.0-beta.3 and the issue is now resolved:

```
npm install 'jspm@0.16.0-beta.3` -g
```

**Comment by felixbillon** [comment]
Thank you that's solve my problem.

**Comment by frankwallis** [comment]
Yes master is now version 2.0 which uses jspm 0.16.

If you still want to use jspm 0.15 then you will need version 1.0 and the example can be found in the '1.0' branch.
