### ISSUE TITLE
Can't run example

### ISSUE THREAD

**Issue by calebbrewer** [frankwallis/plugin-typescript#29]
I tried to run the example and this is the output I get when I run jspm install:

```
err  TypeError: Cannot read property 'forEach' of undefined
         at /usr/local/lib/node_modules/jspm/lib/core.js:212:10
         at tryCatchReject (/usr/local/lib/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:1183:30)
         at runContinuation1 (/usr/local/lib/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:1142:4)
         at Fulfilled.when (/usr/local/lib/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:930:4)
         at ContinuationTask.run (/usr/local/lib/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:1040:24)
         at Scheduler._drain (/usr/local/lib/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:97:19)
         at Scheduler.drain (/usr/local/lib/node_modules/jspm/node_modules/systemjs/node_modules/es6-module-loader/dist/es6-module-loader.src.js:62:9)
         at process._tickCallback (node.js:355:11)
```

Any ideas?

Thanks for making this plugin.

**Comment by frankwallis** [comment]
I think you are running the wrong version of jspm. For master you need the 0.16 beta:

```npm install 'jspm@0.16.0-beta.3' -g```

If you are using jspm 0.15 then please use the example from the 1.0 branch.

**Comment by calebbrewer** [comment]
That Worked. Thanks. 

It would be cool if you put in the dependencies?

**Comment by frankwallis** [comment]
yes, you're right, I've added it now.

**Comment by calebbrewer** [comment]
Cool. Thanks again!
