### ISSUE TITLE
Angular example project doesn't build

### ISSUE THREAD

**Issue by bnolan** [frankwallis/plugin-typescript#51]
I checked out the repo, cd into examples/angular, npm install, install gulp and system-builder and then the `gulp bundle` task complains about ts.js:

```
[Error: ENOENT: no such file or directory, open '/private/tmp/plugin-typescript/example/angular/ts.js']
[15:24:58] 'bundle' errored after 357 ms
[15:24:58] Error: ENOENT: no such file or directory, open '/private/tmp/plugin-typescript/example/angular/ts.js'
    at Error (native)
    Error loading file:///private/tmp/plugin-typescript/example/angular/ts.js
```

Full repro steps:

```
[bnolan@turtle tmp]$ git clone https://github.com/frankwallis/plugin-typescript.git
Cloning into 'plugin-typescript'...
remote: Counting objects: 1448, done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 1448 (delta 8), reused 0 (delta 0), pack-reused 1422
Receiving objects: 100% (1448/1448), 242.20 KiB | 351.00 KiB/s, done.
Resolving deltas: 100% (910/910), done.
Checking connectivity... done.
[bnolan@turtle tmp]$ cd plugin-typescript/
[bnolan@turtle plugin-typescript]$ ls
LICENSE      README.md    example      lib          package.json test
[bnolan@turtle plugin-typescript]$ cd example/angular
[bnolan@turtle angular]$ ls
config.js         index-bundle.html index.html        src
gulpfile.js       index-inject.html package.json      tsconfig.json
[bnolan@turtle angular]$ npm install
npm WARN package.json @ No description
npm WARN package.json @ No repository field.
npm WARN package.json @ No README data
npm WARN package.json @ No license field.
[bnolan@turtle angular]$ gulp
[15:24:21] Local gulp not found in /private/tmp/plugin-typescript/example/angular
[15:24:21] Try running: npm install gulp
[bnolan@turtle angular]$ npm install --save gulp
npm WARN package.json @ No description
npm WARN package.json @ No repository field.
npm WARN package.json @ No README data
npm WARN package.json @ No license field.
gulp@3.9.0 node_modules/gulp
├── interpret@0.6.6
├── pretty-hrtime@1.0.1
├── deprecated@0.0.1
├── archy@1.0.0
├── minimist@1.2.0
├── semver@4.3.6
├── v8flags@2.0.10 (user-home@1.1.1)
├── tildify@1.1.2 (os-homedir@1.0.1)
├── chalk@1.1.1 (supports-color@2.0.0, ansi-styles@2.1.0, escape-string-regexp@1.0.3, strip-ansi@3.0.0, has-ansi@2.0.0)
├── orchestrator@0.3.7 (stream-consume@0.1.0, sequencify@0.0.7, end-of-stream@0.1.5)
├── liftoff@2.2.0 (extend@2.0.1, rechoir@0.6.2, flagged-respawn@0.3.1, resolve@1.1.6, findup-sync@0.3.0)
├── vinyl-fs@0.3.14 (graceful-fs@3.0.8, mkdirp@0.5.1, vinyl@0.4.6, defaults@1.0.3, strip-bom@1.0.0, through2@0.6.5, glob-stream@3.1.18, glob-watcher@0.0.6)
└── gulp-util@3.0.7 (array-uniq@1.0.2, array-differ@1.0.0, object-assign@3.0.0, lodash._reinterpolate@3.0.0, lodash._reescape@3.0.0, fancy-log@1.1.0, beeper@1.1.0, lodash._reevaluate@3.0.0, replace-ext@0.0.1, has-gulplog@0.1.0, gulplog@1.0.0, vinyl@0.5.3, multipipe@0.1.2, through2@2.0.0, lodash.template@3.6.2, dateformat@1.0.11)
[bnolan@turtle angular]$ gulp bundle
[15:24:43] Using gulpfile /private/tmp/plugin-typescript/example/angular/gulpfile.js
[15:24:43] Starting 'bundle'...
[15:24:43] 'bundle' errored after 239 μs
[15:24:43] Error: Cannot find module 'systemjs-builder'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Gulp.<anonymous> (/private/tmp/plugin-typescript/example/angular/gulpfile.js:19:16)
    at module.exports (/private/tmp/plugin-typescript/example/angular/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/private/tmp/plugin-typescript/example/angular/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/private/tmp/plugin-typescript/example/angular/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/private/tmp/plugin-typescript/example/angular/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
[bnolan@turtle angular]$ npm install --save systemjs-builder
npm WARN package.json @ No description
npm WARN package.json @ No repository field.
npm WARN package.json @ No README data
npm WARN package.json @ No license field.
systemjs-builder@0.14.9 node_modules/systemjs-builder
├── rsvp@3.1.0
├── mkdirp@0.5.1 (minimist@0.0.8)
├── algorithms@0.9.1
├── source-map@0.4.4 (amdefine@1.0.0)
├── glob@5.0.15 (path-is-absolute@1.0.0, inherits@2.0.1, once@1.3.2, inflight@1.0.4, minimatch@3.0.0)
├── traceur@0.0.92 (commander@2.6.0, semver@2.3.2, glob@4.3.5, source-map-support@0.2.10)
├── systemjs@0.19.5 (when@3.7.4, es6-module-loader@0.17.8)
├── uglify-js@2.5.0 (uglify-to-browserify@1.0.2, async@0.2.10, source-map@0.5.3, yargs@3.5.4)
└── es6-template-strings@2.0.0 (esniff@1.0.0, es5-ext@0.10.8)
[bnolan@turtle angular]$ gulp bundle
[15:24:58] Using gulpfile /private/tmp/plugin-typescript/example/angular/gulpfile.js
[15:24:58] Starting 'bundle'...
[Error: ENOENT: no such file or directory, open '/private/tmp/plugin-typescript/example/angular/ts.js']
[15:24:58] 'bundle' errored after 357 ms
[15:24:58] Error: ENOENT: no such file or directory, open '/private/tmp/plugin-typescript/example/angular/ts.js'
    at Error (native)
	Error loading file:///private/tmp/plugin-typescript/example/angular/ts.js
```

**Comment by frankwallis** [comment]
The steps should be:

> git clone https://github.com/frankwallis/plugin-typescript.git
> cd plugin-typescript
> npm install
> cd example/angular
> jspm install
> gulp bundle

Can you give that a try and I will update the readme to make it a bit clearer. Thanks.
