### ISSUE TITLE
'Map' is undefined error in IE10

### ISSUE THREAD

**Issue by mikeyoon** [frankwallis/plugin-typescript#70]
Originally posted this in the SystemJS repo, but found out it's more likely something on the transpiler side. Any help would be appreciated.

In IE10 (via the Win7/IE10 VBox VM provided by MS), I get the following exception when loading in my project.

Potentially unhandled rejection [3] ReferenceError: 'Map' is undefined
at CompilerHost (Unknown script code:18:9)
at createServices (Unknown script code:67:5)
at Anonymous function (Unknown script code:16:9)
at M (http://assets.modeanalytics.dev:3001/jspm_packages/system-polyfills.js:4:8723)
at H (http://assets.modeanalytics.dev:3001/jspm_packages/system-polyfills.js:4:8310)
at when (http://assets.modeanalytics.dev:3001/jspm_packages/system-polyfills.js:4:12042)
at run (http://assets.modeanalytics.dev:3001/jspm_packages/system-polyfills.js:4:11076)
at _drain (http://assets.modeanalytics.dev:3001/jspm_packages/system-polyfills.js:4:3014)
at drain (http://assets.modeanalytics.dev:3001/jspm_packages/system-polyfills.js:4:2681)

This is with 2.4.0 and SystemJS 0.19.16. Let me know if there's any other info that would be helpful.

**Comment by frankwallis** [comment]
Thanks, this should be fixed in 2.4.1.
