### ISSUE TITLE
typescript + babel chokes on sourceMap

### ISSUE THREAD

**Issue by andrenarchy** [frankwallis/plugin-typescript#98]
In [my project](https://github.com/andrenarchy/jspm-typescript-es6-boilerplate/tree/3f90cd5a8c1161999fe5d6000cd7dbd620da7fb7) with jspm 0.17.0-beta.5 (typescript+babel), the compilation errors out with
```
Error on translate for src/index.ts at file:///tmp/jspm-test/src/index.ts
  TypeError: file:///tmp/jspm-test/src/index.ts: Cannot assign to read only property 'mappings' of {"version":3,"file":"index.js","sourceRoot":"","sources":["index.ts"],"names":[],"mappings":"AAAA,oBAAoB;AACpB,kBAAkB;;;;;;;;;;;;;;OAEX,EAAC,GAAG,EAAE,KAAK,EAAC,MAAM,SAAS;AAElC,MAAM,IAAI,GAAW,SAAS,CAAC;AAE/B,OAAO,CAAC,GAAG,CAAC,KAAK,EAAE,IAAI,EAAE,GAAG,CAAC,CAAC;AAE9B,CAAC;;QACC,OAAO,CAAC,GAAG,CAAC,QAAQ,CAAC,CAAC;QACtB,MAAM,KAAK,CAAC,IAAI,CAAC,CAAC;QAClB,OAAO,CAAC,GAAG,CAAC,OAAO,CAAC,CAAC;IACvB,CAAC;CAAA,CAAC,EAAE,CAAC;AAEL,OAAO,CAAC,GAAG,CAAC,KAAK,EAAE,IAAI,EAAE,GAAG,CAAC,CAAC"}
    at eval (file:///tmp/jspm-test/jspm_packages/npm/systemjs-plugin-babel@0.0.2/systemjs-babel-node.js:7749:29)
    at File.mergeSourceMap (file:///tmp/jspm-test/jspm_packages/npm/systemjs-plugin-babel@0.0.2/systemjs-babel-node.js:7751:11)
    at File.generate (file:///tmp/jspm-test/jspm_packages/npm/systemjs-plugin-babel@0.0.2/systemjs-babel-node.js:7916:27)
    at File.transform (file:///tmp/jspm-test/jspm_packages/npm/systemjs-plugin-babel@0.0.2/systemjs-babel-node.js:7787:19)
    at eval (file:///tmp/jspm-test/jspm_packages/npm/systemjs-plugin-babel@0.0.2/systemjs-babel-node.js:3904:21)
    at File.wrap (file:///tmp/jspm-test/jspm_packages/npm/systemjs-plugin-babel@0.0.2/systemjs-babel-node.js:7798:18)
    at Pipeline.transform (file:///tmp/jspm-test/jspm_packages/npm/systemjs-plugin-babel@0.0.2/systemjs-babel-node.js:3901:19)
    at eval (file:///tmp/jspm-test/jspm_packages/npm/systemjs-plugin-babel@0.0.2/plugin-babel.js:133:24)
```

It's failing in the babel plugin but the error disappears when I set `"sourceMap": false` in `tsconfig.json` so I assume that the problem is actually in the typescript plugin (which runs before babel). Maybe you can take a look at the code? Let me know if I can be of help for tracking down the issue!

It would certainly be great to re-enable sourcemaps in my project. :smile:

**Comment by frankwallis** [comment]
@guybedford - there seems to be an issue here when providing an inputSourceMap to plugin-babel. plugin-typescript is setting ```metadata.sourceMap``` to the string representation of the source map file. There have been issues in this scenario with babel5 when it needed to JSON.parse the sourceMap and provide it as object but that does not seem to fix this one. Can you confirm whether ```metadata.sourceMap``` should be string or object and I can delve a bit further?

**Comment by guybedford** [comment]
@frankwallis metadata.sourceMap should be an object. I'm including a warning for setting it as a string to be on the deprecation path. I've also fixed up the in-browser Babel source map chaining today and can confirm it's all working correctly pending the coming SystemJS release.

**Comment by frankwallis** [comment]
I think this is all now working, and I've updated the example projects to use jspm@0.17.0-beta.5.
